# Generated by Django 4.1.3 on 2022-11-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='izoh_matni',
        ),
    ]
