# Generated by Django 4.1.3 on 2022-11-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_rename_comment_comment_izoh_matni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
