# Generated by Django 4.1.3 on 2022-11-13 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filmapp', '0003_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh_matni', models.CharField(blank=True, max_length=30)),
                ('sana', models.DateTimeField(auto_now_add=True, null=True)),
                ('kino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmapp.kino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
