# Generated by Django 4.1.3 on 2022-11-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
